# Generated by Django 3.2.6 on 2021-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donee',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
